### ISSUE TITLE
Tornado randomly breaks

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1658]
Version: StepMania5.2-git-ad1ed0b on Ubuntu 16.04.4, 64-bit
In 5.2, there appears to be some instances where Tornado might not be initialized correctly, resulting in column notes disappearing, column receptors moving around, or a combination of both.
TornadoZ also appears to be affected by this (though, it seemed a bit harder to trigger on TornadoZ).
This does not seem to appear in 5.1-new/5.0
I don't know what exactly causes this.

The column or player it happens on is different whenever the bug happens.
The severity of the bug differs every time it happens.
Restarting the song may either resolve the issue for that run, or cause a different variation.
I feel like I had an easier time causing this to happen in HD themes (ex: Lambda/new default), as opposed to SD themes (ex: Simply Love, old default).

Pictures showing the bug and intended functionality: [https://imgur.com/a/9smsA](https://imgur.com/a/9smsA)
Lua script demonstrating the bug on Tornado: [https://hastebin.com/pugirararo.rb](https://hastebin.com/pugirararo.rb)
The lua script was run as a FGCHANGE.

**Comment by kyzentun** [comment]
I'm going to take a shot in the dark, and suggest calling ArrowDefects::Init at the end of ArrowDefects::set_column_pos.  Init uses the column positions set by set_column_pos, so it should run when they change anyway.

```
void ArrowDefects::set_column_pos(std::vector<float>& column_x)
{
  ... <function body>
  Init();
}
```
```Init();``` should be the very last line in the set_column_pos function.

The current code probably also misbehaves if the player changes to a noteskin with a different column width during the song.  I think one of the hanubeki noteskins has a width of 32.  Calling Init when the new positions are set should fix that too.

**Comment by MrThatKid** [comment]
The bug still randomly happens even with Init being called at the end of set_column_pos.
However, it does fix the issue you mentioned, as now tornado acts accordingly (when it doesn't break) when switching between noteskins that have different column widths.
At this point, with the above change, resetting the noteskin/switching to another one sometimes fixes it, but it doesn't always work.

**Comment by MrThatKid** [comment]
I'll try to test it later today. Also, if this were a windows only bug, I'd think I shouldn't have this issue because I'm using linux, but I run into it anyway.

**Comment by MrThatKid** [comment]
Okay, so I've gotten some results from the first commit. First thing to note is that the isnan and !isfinite checks don't detect the bug.
Here's the lines from the print statement: [https://pastebin.com/kaaG6MUA](https://pastebin.com/kaaG6MUA)
It's been slightly edited to show intended behavior at the top, and otherwise only shows batches with anomalous behavior.
Here's the screenshots that correspond to the batches: [https://imgur.com/a/HlD2A](https://imgur.com/a/HlD2A)

Here's things to note from this: max_x is shown as a huge number when columns disappear. Also, the values for rads and normalized show the values expected for column 0 when max_x shows bad values.
Another thing to note is that start_col and end_col show values that appear to be out of the range of valid columns, but this also happens on the normal set.

I have yet to test seeing how the period and offset get affected when max_x shows bad values, and I'll need to do some testing with the new commit.

**Comment by kyzentun** [comment]
This commit should fix the problem.  https://github.com/kyzentun/stepmania/commit/0e0f766a1631aa1c2022e464077d728603d5cadc

An older version of clamp modified its first arg instead of returning the value, and the start_col and end_col clamp lines were based on that behavior.

**Comment by MrThatKid** [comment]
I think it has fixed the problem. I don't seem to be able to reproduce the bug with that change in place.

**Comment by MrThatKid** [comment]
Fixed in #1659
